# Generated by Django 5.1.5 on 2025-01-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensage',
            new_name='Message',
        ),
    ]
