# Generated by Django 5.1.5 on 2025-01-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_rename_mensage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
