# Generated by Django 5.1.5 on 2025-01-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_message_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created',
        ),
    ]
