# Generated by Django 5.1.5 on 2025-02-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_message_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('number', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NA', 'Prefiro não informar')], max_length=150)),
                ('procedure', models.CharField(max_length=150)),
            ],
        ),
    ]
