# Generated by Django 5.1.5 on 2025-02-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='media/pacientes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
