# Generated by Django 5.1.5 on 2025-02-10 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pacientes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='in_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='procedure_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
