# Generated by Django 5.1.5 on 2025-02-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_remove_file_arquivo_file_file_paciente_in_care_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
