# Generated by Django 5.1.5 on 2025-02-21 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_message_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='whatsapp.doctor'),
            preserve_default=False,
        ),
    ]
