# Generated by Django 5.1.5 on 2025-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_doctor_paciente_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
